import type { NextPage } from "next"
import Head from "next/head"
import { useSession } from "next-auth/client"

import { AuthCheck } from "@/components/AuthCheck"
import Header from "@/components/Header"
import { WatchingAnimeContainer } from "@/components/WatchingAnime"

const Home: NextPage = () => {
  const [session, _] = useSession()
  return (
    <AuthCheck>
      <Head>
        <title>Panino</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header user={session?.user} />
      <WatchingAnimeContainer />
    </AuthCheck>
  )
}

export default Home
