import type { NextPage } from "next"
import Head from "next/head"
import { useSession } from "next-auth/client"

import { AuthCheck } from "@/components/AuthCheck"
import { LoginWithAnnict } from "@/components/LoginWithAnnict"

const Index: NextPage = () => {
  const [session, loading] = useSession()
  return (
    <AuthCheck>
      <Head>
        <title>Panino</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoginWithAnnict />
    </AuthCheck>
  )
}

export default Index
