import type { NextPage } from "next"
import Head from "next/head"
import { useSession } from "next-auth/client"

import Header from "../components/Header"
import { Loading } from "../components/Loading"
import { LoginWithAnnict } from "../components/LoginWithAnnict"

const Home: NextPage = () => {
  const [session, loading] = useSession()
  return (
    <>
      <Head>
        <title>Panino</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!session && <>{loading ? <Loading /> : <LoginWithAnnict />}</>}
      {session && (
        <>
          <Header user={session.user} />
          <h1>Hello {session.user?.name}</h1>
        </>
      )}
    </>
  )
}

export default Home
