import { Container } from "@chakra-ui/layout"
import type { NextPage } from "next"
import Head from "next/head"
import { useSession } from "next-auth/client"

import Header from "../components/Header"
import { Loading } from "../components/Loading"
import { LoginWithAnnict } from "../components/LoginWithAnnict"

const Home: NextPage = () => {
  const [session, loading] = useSession()
  return (
    <>
      <Head>
        <title>Panino</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!session && (
        <>
          {loading ? (
            <Loading />
          ) : (
            <Container>
              <LoginWithAnnict />
            </Container>
          )}
        </>
      )}
      {session && <Header user={session.user} />}
    </>
  )
}

export default Home
