import { Container } from "@chakra-ui/layout"
import type { NextPage } from "next"
import Head from "next/head"

import Header from "../components/Header"
import { LoginWithAnnict } from "../components/LoginWithAnnict"

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Panino</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Container>
        <LoginWithAnnict />
      </Container>
    </>
  )
}

export default Home
